name: Gatsby
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "README.md"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

concurrency:
  group: release-ci-group
  cancel-in-progress: false

jobs:
  release-and-page:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
          registry-url: "https://registry.yarnpkg.com"

      - name: Install Dependency
        run: |
          yarn install --production

      - name: Build
        run: |
          # yarn run build
          npx gatsby build --prefix-paths

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: |
            ./public
